# Generated by Django 4.2.7 on 2025-09-20 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="employee_id",
        ),
    ]
