# Generated by Django 4.2.7 on 2025-09-20 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Review"),
                            ("quarterly", "Quarterly Review"),
                            ("probation", "Probation Review"),
                            ("mid_year", "Mid-Year Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("review_period_start", models.DateField()),
                ("review_period_end", models.DateField()),
                (
                    "technical_skills",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Above Average"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "communication",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Above Average"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "teamwork",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Above Average"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "leadership",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Above Average"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "productivity",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Above Average"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "achievements",
                    models.TextField(help_text="Key achievements during review period"),
                ),
                (
                    "areas_for_improvement",
                    models.TextField(help_text="Areas needing improvement"),
                ),
                (
                    "goals_for_next_period",
                    models.TextField(help_text="Goals for next review period"),
                ),
                ("reviewer_comments", models.TextField(blank=True)),
                ("employee_comments", models.TextField(blank=True)),
                ("overall_rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_finalized", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
