# Generated by Django 4.2.7 on 2025-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavebalance",
            name="annual_leave",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="casual_leave",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="sick_leave",
            field=models.IntegerField(default=3),
        ),
    ]
