# Generated by Django 4.2.7 on 2025-09-12 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaveapplication",
            old_name="hr_comments",
            new_name="admin_comments",
        ),
        migrations.RenameField(
            model_name="leaveapplication",
            old_name="final_approved_at",
            new_name="approved_at",
        ),
        migrations.RemoveField(
            model_name="leaveapplication",
            name="final_approved_by",
        ),
        migrations.RemoveField(
            model_name="leaveapplication",
            name="hr_approved_at",
        ),
        migrations.RemoveField(
            model_name="leaveapplication",
            name="hr_approved_by",
        ),
        migrations.RemoveField(
            model_name="leaveapplication",
            name="manager_approved_at",
        ),
        migrations.RemoveField(
            model_name="leaveapplication",
            name="manager_approved_by",
        ),
        migrations.RemoveField(
            model_name="leaveapplication",
            name="manager_comments",
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
