# Generated by Django 4.2.7 on 2025-09-12 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0002_rename_hr_comments_leaveapplication_admin_comments_and_more"),
    ]

    operations = []
