# Generated by Django 4.2.7 on 2025-09-13 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leaves", "0003_auto_20250913_0138"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="admin_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="admin_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="admin_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="hr_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="hr_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="hr_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="hr_comments",
            field=models.TextField(blank=True),
        ),
    ]
