# Generated by Django 4.2.7 on 2025-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0004_leaveapplication_admin_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaveapplication",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="leaveapplication",
            name="approved_by",
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending HR Review"),
                    ("hr_approved", "HR Approved - Pending Admin"),
                    ("approved", "Fully Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
